# Generated by Django 2.0.2 on 2018-02-17 01:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show_portfolio', '0002_auto_20180216_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 1, 15, 31, 358892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 1, 15, 31, 358193, tzinfo=utc)),
        ),
    ]
