# Generated by Django 2.0.2 on 2018-02-17 01:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show_portfolio', '0003_auto_20180217_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 1, 16, 54, 107933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 1, 16, 54, 106898, tzinfo=utc)),
        ),
    ]
