# Generated by Django 2.0.2 on 2018-02-17 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show_portfolio', '0004_auto_20180217_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Data', 'Data'), ('PyJava', 'PyJava'), ('iOS/Misc', 'iOS/Misc')], default='Data', max_length=15),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 16, 8, 34, 227563, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 16, 8, 34, 226854, tzinfo=utc)),
        ),
    ]
