# Generated by Django 2.0.2 on 2018-02-18 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import show_portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('show_portfolio', '0008_auto_20180218_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=show_portfolio.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 18, 18, 18, 48, 293023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 18, 18, 18, 48, 293023, tzinfo=utc)),
        ),
    ]
