# Generated by Django 2.0.2 on 2018-02-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_portfolio', '0012_auto_20180218_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
